kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world

# steps:
# - name: build
#   image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
#   commands:
#   - dotnet build