pipeline:

  build:
    image: mcr.microsoft.com/dotnet/sdk:5.0.202-alpine3.12
    commands:
      - dotnet restore --no-cache
      - dotnet build

  generate_docs:
    image: alpine:3.12
    commands:
      - ./scripts/generate_docs.sh
    when:
      event: push
      branch: [master, develop, cicd_test]

  deploy_docs:
    image: drillster/drone-rsync
    source: ./docs/
    target: ~/html/libsmb2sharp/
    delete: true
    args: "--verbose"
    secrets:
      - source: doc_deploy_key
        target: plugin_key
      - source: doc_deploy_server
        target: plugin_hosts
      - source: doc_deploy_user
        target: plugin_user
    when:
      event: push
      branch: [master, develop]

  prepare_publish:
    image: alpine:3.12
    commands:
      - ./scripts/prepare_publish.sh
    when:
      event: tag
      tag: release/*

  gitea_release:
    image: plugins/gitea-release
    base_url: https://git.foxhollow.cc
    title: "LibSMB2Sharp ${DRONE_TAG##release/}"
    note: RELEASE_NOTES.md
    # find some way to programmatically set the draft flag
    # draft: true
    files:
      - dist/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    secrets:
      - source: release_key
        target: plugin_api_key
    when:
      event: tag
      tag: release/*

  publish_nuget:
    image: mcr.microsoft.com/dotnet/sdk:5.0.202-alpine3.12
    commands:
      - dotnet nuget push *.nupkg --api-key $NUGET_PUBLISH_KEY
      # - dotnet nuget push *.nupkg --api-key $NUGET_PUBLISH_KEY --source https://api.nuget.org/v3/index.json
    environment: [nuget_publish_key]
    when:
      event: tag
      tag: release/*

# Create tags with release/v1.0.0-beta2, etc


# On tag, check tag version against version in Directory.Build.props, if they don't match.. fail the build
# if they match
#   build the project
#   create zip and tarball, push to gitea
#   push package to nuget

# On push 
#   build the project
#   push docs to web

